name: Fully compile build and upload to Test Pypi
on:
  push:
    tags:
      - v* #tag starting with v

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Python
        uses: actions/setup-python@c4e89fac7e8767b327bbad6cb4d859eda999cf08
        with:
          python-version: "3.9"
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Install build dependency
        run: python3 -m pip install -r requirements-build.txt

      - name: build
        run: python3 -m build

      - name: List shasums
        run: shasum -a 256 dist/*

