name: Fully compile build and upload to Test Pypi
on:
  push:
    tags:
      - v* #tag starting with v

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Python
        uses: actions/setup-python@c4e89fac7e8767b327bbad6cb4d859eda999cf08
        with:
          python-version: "3.9"
